
extends Node2D

var TILE_SIZE_X = 64
var TILE_SIZE_Y = 32
var DISTANCE_LEFT = Vector2(-TILE_SIZE_X, TILE_SIZE_Y)
var DISTANCE_RIGHT = Vector2(TILE_SIZE_X, -TILE_SIZE_Y)
var DISTANCE_UP = Vector2(-TILE_SIZE_X, -TILE_SIZE_Y)
var DISTANCE_DOWN = Vector2(TILE_SIZE_X, TILE_SIZE_Y)
var GAME_TICK = .5